### ISSUE TITLE
Rework the entire Application based on MVC architecture

### ISSUE THREAD

**Issue by iHaroon29** [rishthekingboy/Blog#15]
I was going through your project and found that it's written in a single file. I felt it could have been written better. So, I cloned your project and made changes accordingly. Add me as a contributor, so I can push my code and you might PR it.

**Comment by rishthekingboy** [comment]
> I was going through your project and found that it's written in a single file. I felt it could have been written better. So, I cloned your project and made changes accordingly. Add me as a contributor, so I can push my code and you might PR it.

@iHaroon29 I started this as a practice project when i was new in Nodejs but i got forgot about this repo later, so i can understand how much you need to rework on it. I appreciate your efforts, feel free to reach out to me if you need any kind of help
